# introduce
Numpy是Python语言进行科学计算必要的Model。Numpy支持Python的数值计算扩充库，其中包含了许多强大的功能：处理多维数组以及矩阵运算。NumPy（Numerical Python），面向数值计算的第三方库。

## basic
- 数值类型 & 多维数组
- 数组操作 & 随机抽样
- 数学函数 & 代数运算
- 数组索引 & Others

## NumPy数组类型
![](https://cdn.jsdelivr.net/gh/Lyli724/Blogs_image@master/uPic/JjozOV.png)
> 在NumPy中的这些数值类型我们常常使用dtype(data)来查看data数据的类型，使用numpy.dtype(object, align, copy)来指定数据类型。在数组中，使用dtype = 参数

In [1]:
import numpy as np # 导入Numpy

# 指定数组中的数值类型为float64
a = np.array([6.6, 66.6, 666.6], dtype = np.float64) 
a, a.dtype

(array([  6.6,  66.6, 666.6]), dtype('float64'))

In [2]:
# 使用np.astype()方法将不同的数值类型之间相互转换
a.astype(int).dtype, a

(dtype('int64'), array([  6.6,  66.6, 666.6]))

## NumPy创建数组
在Python内建对象中，数组有以下三种形式：
- list(列表)：[1, 2, 3]
- tuple(元组)：(1, 2, 3)
- dict(字典)：{1: 1, 2: 2, 3: 3}

其中，元组与列表的操作相似，但是元组中的元素是不可修改的，列表则可以修改。字典是以键值对形式存在。python标准类对数组的处理仅仅局限于1维数组，而且对数学运算不是很好的支持。NumPy中最核心的是多维数组ndarray，它对高维数组具有较好的数值计算能力。

NmuPy中的ndarray具有以下特点
- shape: 数组的形状（几行几列）
- dtype: 数据类型
- buffer: 对象暴露缓冲区接口
- offset: 数组数据的偏移量
- strides: 数据步长
- order: {'C', 'F'}, 以行或者列为主排列顺序。

NumPy创建多维数组的一些方法
- 从Python数组结构列表， 元组等转换。
- 使用np.arange、 np.ones、 NP.zeros等NumPy原生方法创建。
- 从存储空间读入数组。
- 通过使用字符串或缓冲区从原始字节创建数组
- 使用特殊函数， 如random

### list or tuple转换
在NumPy中，我们使用numpy.array将列表或元组转换为ndarray数组。
```python
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```
其中，参数：
- object：列表、元组等。
- dtype：数据类型。如果未给出，则类型为被保存对象所需的最小类型。
- copy：布尔类型，默认 True，表示复制对象。
- order：顺序。
- subok：布尔类型，表示子类是否被传递。
- ndmin：生成的数组应具有的最小维数。
下面，通过列表创建一个 ndarray 数组。

In [3]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array([(1, 2), (3, 4), (5, 6)])

array([[1, 2],
       [3, 4],
       [5, 6]])

### arrage创建数组
除了直接使用array方法创建ndarray，在NumPy中还有一些方法可以创建一些有规律的多维数组。首先，我们来看一看arange()。arange()的功能是在给定区间内创建一系列均匀间隔的值。
```python
numpy.arange(start, stop, step, dtype = None)
```
你需要设置区间的起始值和结束值，[start, stop)左闭右开区间。设置step步长间隔。dtype可以返回ndarray的类型。

In [5]:
np.arange(3, 10, 0.2, dtype = 'float64')

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4,
       5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. ,
       8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

### linspace创建数组
linspace方法类似于arange方法，创建数值有规律的数组。linspace用于指定的区间内返回间隔均匀的值
```python
numpy.linspace(start, stop, num = 50, endpoint = True, restep = False, dtype = None)
```
- start：序列的起始值。
- stop：序列的结束值。
- num：生成的样本数。默认值为50。
- endpoint：布尔值，如果为真，则最后一个样本包含在序列内。
- retstep：布尔值，如果为真，返回间距。
- dtype：数组的类型。

In [8]:
np.linspace(0, 20, 10, endpoint = True, dtype = 'int64')

array([ 0,  2,  4,  6,  8, 11, 13, 15, 17, 20])

In [9]:
np.linspace(0, 20, 10, endpoint = False, dtype = 'int64')

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### ones创建数组
numpy.ones用于快速创建数值全部为1的多维数组。
```python
numpy.ones(shape, dtype = None, order = 'C')
```
- shape：用于指定数组形状，例如（1， 2）或 3, 传入元组。
- dtype：数据类型。
- order：{'C'，'F'}，按行或列方式储存数组。

In [11]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### zeros创建数组
numpy.zeros用于快速创建数值全为0的多维数组
```python
numpy.zeros(shape, dtype = None, order = 'C')
```
- shape：用于指定数组形状，例如（1， 2）或 3, 传入元组。
- dtype：数据类型。
- order：{'C'，'F'}，按行或列方式储存数组。

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### eye创建数组
numpy.eye用于创建一个二维数组，其特点是k对角线上为1，其余值全部为0。
```python
numpy.eye(N, M = None, k = 0, dtype = <type 'float'>)
```
N：输出数组的行数。
M：输出数组的列数。
k：对角线索引：0（默认）是指主对角线，正值是指上对角线，负值是指下对角线。

In [15]:
np.eye(5, 4, 3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### 已知数据创建数组
我们可以从硬盘上的数据文件、函数创建ndarray。NumPy提供以下方法进行创建：
- frombuffer（buffer）：将缓冲区转换为 1 维数组。
- fromfile（file，dtype，count，sep）：从文本或二进制文件中构建多维数组。
- fromfunction（function，shape）：通过函数返回值来创建多维数组。
- fromiter（iterable，dtype，count）：从可迭代对象创建 1 维数组。
- fromstring（string，dtype，count，sep）：从字符串中创建 1 维数组。

In [17]:
np.fromfunction(lambda a, b: a + b, (5, 4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.],
       [4., 5., 6., 7.]])

### ndarray数组属性
ndarray.T用于数组的转置， 与.transpose()相同。
ndarray.imag用于输出数组包含元素的虚部。
ndarray.real用来输出数组包含元素的实部。
ndarray.size用于输出数组中包含的所有元素个数。
ndarray.itemsize用来输出一个数组的元素字节数。
ndarray.nbytes用来输出数组的总元素的总字节数。
ndarray.ndim用来输出数组维度。
ndarray.shape用来输出数组形状。
ndarray.strides用来遍历数组时，输出每个维度中步进的字节数组。

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a  # 查看 a 的值

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
a.dtype

dtype('int64')

In [21]:
a.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
a.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a.size

9

In [24]:
a.itemsize

8

In [25]:
a.nbytes

72

In [26]:
a.ndim

2

In [27]:
a.shape

(3, 3)

In [28]:
a.strides

(24, 8)

### 数组的维度和形状
前面，我们已经对 NumPy 数组的类型和常用的生成方法进行了介绍。再继续了解更多内容前，必须先搞清楚一个重要的问题，那就是 NumPy 数组的维度和形状。
NumPy 数组又被称之为 ndarray 多维数组，那么 n 就可以从 1 维依次递增。下图，我们展示了 1 至 3 维的 NumPy 数组示例。
![](https://cdn.jsdelivr.net/gh/Lyli724/Blogs_image@master/uPic/zo9db8.png)
> 1 维数组可以被看作数学中的向量.
2 维数组可以看作是矩阵.
3 维数组则是一个数据立方.

In [29]:
first_array = np.array([7, 2, 9, 10])
second_array = np.array([[5.2, 3.0, 4.5],
                [9.1, 0.1, 0.3]])
third_array = np.array([[[1, 1], [1, 1], [1, 1]],
                  [[1, 1], [1, 1], [1, 1]],
                  [[1, 1], [1, 1], [1, 1]],
                  [[1, 1], [1, 1], [1, 1]]])
first_array, second_array, third_array

(array([ 7,  2,  9, 10]),
 array([[5.2, 3. , 4.5],
        [9.1, 0.1, 0.3]]),
 array([[[1, 1],
         [1, 1],
         [1, 1]],
 
        [[1, 1],
         [1, 1],
         [1, 1]],
 
        [[1, 1],
         [1, 1],
         [1, 1]],
 
        [[1, 1],
         [1, 1],
         [1, 1]]]))

In [31]:
first_array.shape, second_array.shape, third_array.shape
# 你可以发现规律，.shape 得到的形状实际上是数组在每个轴 Axis 上面的元素数量，而 .shape 的长度的表明了数组的维度。

((4,), (2, 3), (4, 3, 2))

### 数组的基本操作
#### 重塑形状
reshape 可以在不改变数组数据的同时，改变数组的形状。其中，numpy.reshape() 等效于 ndarray.reshape()。reshape 方法非常简单：
```python
numpy.reshape(a, newshape) # newshape指得失新的形状（整数或者元组）
```

In [32]:
np.arange(10).reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 展开数组
ravel 的目的是将任意形状的数组扁平化，变为 1 维数组。ravel 方法如下：
```python
numpy.ravel(a, order = 'C')
```
其中，a 表示需要处理的数组。order 表示变换时的读取顺序，默认是按照行依次读取，当 order='F' 时，可以按列依次读取排序。

In [33]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.ravel(a, order = 'F')

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

#### 轴移动
moveaxis可以将数组的轴移动到新的位置。
```python 
numpy.moveaxis(a, source, destination)
```
其中：
a：数组。
source：要移动的轴的原始位置。
destination：要移动的轴的目标位置。

In [38]:
a = np.ones((1, 2, 3))
np.moveaxis(a, 0, -1)

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [45]:
a.shape, np.moveaxis(a, 0, -1).shape
# 因为维度没有-1的存在，所以相当于把1，2，3循环往左移位

((1, 2, 3), (2, 3, 1))

#### 轴交换
swapaxes可以用来交换数组的轴
```python
numpy.swapaxes(a, axis1, axis2)
```
- a：数组。
- axis1：需要交换的轴 1 位置。
- axis2：需要与轴 1 交换位置的轴 1 位置。

In [46]:
a = np.ones((1, 4, 3))
np.swapaxes(a, 0, 2)

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

In [48]:
a.shape, np.swapaxes(a, 0, 2).shape

((1, 4, 3), (3, 4, 1))

#### 数组转置
transpose 类似于矩阵的转置，将二维数组的行列交换
```python
numpy.transpose(a, axes = None)
```
- a：数组。
- axis：该值默认为 none，表示转置。如果有值，那么则按照值替换轴。

In [49]:
a = np.arange(4).reshape(2, 2)
np.transpose(a)

array([[0, 2],
       [1, 3]])

#### 维度改变
atleast_xd支持将输入数据直接看作x维。这里的x可以表示：1， 2， 3。方法
> numpy.atleast_1d()
numpy.atleast_2d()
numpy.atleast_3d()


In [54]:
print(np.atleast_1d([1, 2, 3]))
print(np.atleast_2d([4, 5, 6]))
print(np.atleast_3d([7, 8, 9]))

[1 2 3]
[[4 5 6]]
[[[7]
  [8]
  [9]]]


#### 类型转换
在 NumPy 中，还有一系列以 as 开头的方法，它们可以将特定输入转换为数组，亦可将数组转换为矩阵、标量，ndarray 等。如下：
    
- asarray(a，dtype，order)：将特定输入转换为数组。
- asanyarray(a，dtype，order)：将特定输入转换为 ndarray。
- asmatrix(data，dtype)：将特定输入转换为矩阵。
- asfarray(a，dtype)：将特定输入转换为 float 类型的数组。
- asarray_chkfinite(a，dtype，order)：将特定输入转换为数组，检查 NaN 或 infs。
- asscalar(a)：将大小为 1 的数组转换为标量。

In [55]:
a = np.arange(4).reshape(2, 2)
np.asmatrix(a)

matrix([[0, 1],
        [2, 3]])

In [57]:
type(np.asmatrix(a))

numpy.matrix

In [62]:
a = [[1, 2] , [3, 4]]
np.asarray(a, dtype = 'int')

array([[1, 2],
       [3, 4]])

In [60]:
a = [[1, 2], [3, 4]]
np.asanyarray(a)

array([[1, 2],
       [3, 4]])

In [64]:
a = np.arange(1).reshape(1)
a

array([0])

In [66]:
res = np.asscalar(a)
res

0

#### 数组连接
concatenate可以将多个数组沿指定轴连接在一起。
```pyhton
numpy.concatenate((a1, a2, ... an), axis = 0)
```
- (a1, a2, ...an)：需要连接的数组。
- axis：指定连接轴。

In [67]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[-1, -2], [-3, -4]])
c = np.array([[7, 8]])
np.concatenate((a, b, c), axis = 0) # axis = 0, 按照纵轴连接
# axis = 0:按照纵轴操作
# axis = 1:按照横轴操作
# 具体什么是横轴和纵轴，你将数组按照矩阵形式画在纸上就明白了

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [-1, -2],
       [-3, -4],
       [ 7,  8]])

In [68]:
a = np.array([[1, 2], [3, 4], [7, 8]])
b = np.array([[7, 8, 9]])
np.concatenate((a, b.T), axis = 1) # 按横轴连接

array([[1, 2, 7],
       [3, 4, 8],
       [7, 8, 9]])

#### 数组堆叠
在NumPy中，数组的堆叠常用的方法如下：

- stack(arrays，axis)：沿着新轴连接数组的序列。
- column_stack()：将 1 维数组作为列堆叠到 2 维数组中。
- hstack()：按水平方向堆叠数组。
- vstack()：按垂直方向堆叠数组。
- dstack()：按深度方向堆叠数组。

In [71]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.stack((a, b), axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 数组拆分
- split(ary，indices_or_sections，axis)：将数组拆分为多个子数组。
- dsplit(ary，indices_or_sections)：按深度方向将数组拆分成多个子数组。
- hsplit(ary，indices_or_sections)：按水平方向将数组拆分成多个子数组。
- vsplit(ary，indices_or_sections)：按垂直方向将数组拆分成多个子数组。

In [73]:
a = np.arange(10) # 拆分一维数组
np.split(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [74]:
a = np.arange(10).reshape(2, 5)
np.split(a, 2) # 按两行拆分

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

#### 删除delete
- delete(arr, obj, axis):沿特定轴删除数组的子数组

In [75]:
a = np.arange(12).reshape(3, 4)
np.delete(a, 2, 1) # 这里代表沿着横轴，将第 3 列(索引 2)删除。

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

In [76]:
np.delete(a, 2, 0)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#### 数组插入
- insert(arr, obj, values, axis):依据索引在特定轴之前插入值。

In [77]:
a = np.arange(12).reshape(3, 4)
b = np.arange(4)

np.insert(a, 2, b, 0) # axis = 0是操作行， 在索引第二行插入b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

#### 数组附加
append 的用法也非常简单。只需要设置好需要附加的值和轴位置就好了。它其实相当于只能在末尾插入的 insert，所以少了一个指定索引的参数。

- append(arr，values，axis)：将值附加到数组的末尾，并返回 1 维数组

In [78]:
a = np.arange(6).reshape(2, 3)
b = np.arange(3)

np.append(a, b)

array([0, 1, 2, 3, 4, 5, 0, 1, 2])

#### 重设尺寸
- resize(a, new_shape):对数组尺寸重新设定
> reshape和resize区别  
其实，它们是有区别的，区别在于对原数组的影响。reshape 在改变形状时，不会影响原数组，相当于对原数组做了一份拷贝。而 resize 则是对原数组执行操作。

In [79]:
a = np.arange(10)
a.resize(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 翻转数组
- fliplr(m):左右翻转数组, 以数组的纵向中心对称翻转。
- flipud(m):上下翻转数组， 以数组的横向中心对称翻转

In [82]:
a = np.arange(16).reshape(4, 4)
print(a)
print()
print(np.fliplr(a))
print()
print(np.flipud(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [83]:
a = np.arange(9).reshape(3, 3)
print(a)
print()
print(np.fliplr(a))
print()
print(np.flipud(a))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]


#### NumPy随机数
NumPy 的随机数功能非常强大，主要由 numpy.random 模块完成。

首先，我们需要了解如何使用 NumPy 也就是生成一些满足基本需求的随机数据。主要由以下一些方法完成：

- numpy.random.rand(d0, d1, ..., dn) 方法的作用为：指定一个数组，并使用 [0, 1) 区间随机数据填充，这些数据均匀分布。

- numpy.random.randn(d0, d1, ..., dn) 与 numpy.random.rand(d0, d1, ..., dn) 的区别在于，前者是从标准正态分布中返回一个或多个样本值。

- randint(low, high, size, dtype) 方法将会生成 [low, high) 的随机整数。注意这是一个半开半闭区间。
- random_sample(size) 方法将会在 [0, 1) 区间内生成指定 size 的随机浮点数。

In [84]:
np.random.rand(2, 5)

array([[0.26450387, 0.51014817, 0.91940344, 0.69000074, 0.58635516],
       [0.60717632, 0.4317119 , 0.303312  , 0.48664617, 0.61587315]])

In [85]:
np.random.randn(1, 10)

array([[-0.27956705, -0.02688687, -0.33483695, -1.44483636, -1.12423356,
        -0.50086933,  1.00804803, -0.79393855,  1.31128082, -0.25372302]])

In [86]:
np.random.randint(2, 5, 10)

array([4, 3, 3, 2, 3, 3, 2, 3, 4, 3])

In [87]:
np.random.random_sample([10])

array([0.22338784, 0.94691871, 0.24057428, 0.79561182, 0.64142989,
       0.70335213, 0.71338309, 0.69159151, 0.28677573, 0.97409472])

> 与 numpy.random.random_sample 类似的方法还有：  numpy.random.random([size])
  numpy.random.ranf([size])
  numpy.random.sample([size])  

choice(a, size, replace, p) 方法将会给定的数组里随机抽取几个值，该方法类似于随机抽样。

In [90]:
a = np.arange(10)
np.random.choice(10, 5)

array([3, 5, 6, 2, 5])

#### 概率密度分布
常用方法：
- numpy.random.beta(a，b，size)：从 Beta 分布中生成随机数。
- numpy.random.binomial(n, p, size)：从二项分布中生成随机数。
- numpy.random.chisquare(df，size)：从卡方分布中生成随机数。
- numpy.random.dirichlet(alpha，size)：从 Dirichlet 分布中生成随机数。
- numpy.random.exponential(scale，size)：从指数分布中生成随机数。
- numpy.random.f(dfnum，dfden，size)：从 F 分布中生成随机数。
- numpy.random.gamma(shape，scale，size)：从 Gamma 分布中生成随机数。
- numpy.random.geometric(p，size)：从几何分布中生成随机数。
- numpy.random.gumbel(loc，scale，size)：从 Gumbel 分布中生成随机数。
- numpy.random.hypergeometric(ngood, nbad, nsample, size)：从超几何分布中生成随机数。
- numpy.random.laplace(loc，scale，size)：从拉普拉斯双指数分布中生成随机数。
- numpy.random.logistic(loc，scale，size)：从逻辑分布中生成随机数。
- numpy.random.lognormal(mean，sigma，size)：从对数正态分布中生成随机数。
- numpy.random.logseries(p，size)：从对数系列分布中生成随机数。
- numpy.random.multinomial(n，pvals，size)：从多项分布中生成随机数。
- numpy.random.multivariate_normal(mean, cov, size)：从多变量正态分布绘制随机样本。
- numpy.random.negative_binomial(n, p, size)：从负二项分布中生成随机数。
- numpy.random.noncentral_chisquare(df，nonc，size)：从非中心卡方分布中生成随机数。
- numpy.random.noncentral_f(dfnum, dfden, nonc, size)：从非中心 F 分布中抽取样本。
- numpy.random.normal(loc，scale，size)：从正态分布绘制随机样本。
- numpy.random.pareto(a，size)：从具有指定形状的 Pareto II 或 Lomax 分布中生成随机数。
- numpy.random.poisson(lam，size)：从泊松分布中生成随机数。
- numpy.random.power(a，size)：从具有正指数 a-1 的功率分布中在 0，1 中生成随机数。
- numpy.random.rayleigh(scale，size)：从瑞利分布中生成随机数。
- numpy.random.standard_cauchy(size)：从标准 Cauchy 分布中生成随机数。
- numpy.random.standard_exponential(size)：从标准指数分布中生成随机数。
- numpy.random.standard_gamma(shape，size)：从标准 Gamma 分布中生成随机数。
- numpy.random.standard_normal(size)：从标准正态分布中生成随机数。
- numpy.random.standard_t(df，size)：从具有 df 自由度的标准学生 t 分布中生成随机数。
- numpy.random.triangular(left，mode，right，size)：从三角分布中生成随机数。
- numpy.random.uniform(low，high，size)：从均匀分布中生成随机数。
- numpy.random.vonmises(mu，kappa，size)：从 von Mises 分布中生成随机数。
- numpy.random.wald(mean，scale，size)：从 Wald 或反高斯分布中生成随机数。
- numpy.random.weibull(a，size)：从威布尔分布中生成随机数。
- numpy.random.zipf(a，size)：从 Zipf 分布中生成随机数。

### 数学函数
#### 三角函数
- numpy.sin(x)：三角正弦。
- numpy.cos(x)：三角余弦。
- numpy.tan(x)：三角正切。
- numpy.arcsin(x)：三角反正弦。
- numpy.arccos(x)：三角反余弦。
- numpy.arctan(x)：三角反正切。
- numpy.hypot(x1,x2)：直角三角形求斜边。
- numpy.degrees(x)：弧度转换为度。
- numpy.radians(x)：度转换为弧度。
- numpy.deg2rad(x)：度转换为弧度。
- numpy.rad2deg(x)：弧度转换为度。

In [91]:
np.sin(0)

0.0

In [92]:
np.rad2deg(np.pi)

180.0

#### 双曲函数
在数学中，双曲函数是一类与常见的三角函数类似的函数。双曲函数经常出现于某些重要的线性微分方程的解中，使用 NumPy 计算它们的方法为：
     
- numpy.sinh(x)：双曲正弦。
- numpy.cosh(x)：双曲余弦。
- numpy.tanh(x)：双曲正切。
- numpy.arcsinh(x)：反双曲正弦。
- numpy.arccosh(x)：反双曲余弦。
- numpy.arctanh(x)：反双曲正切。

#### 数值修约
数值修约, 又称数字修约, 是指在进行具体的数字运算前, 按照一定的规则确定一致的位数, 然后舍去某些数字后面多余的尾数的过程。比如, 我们常听到的「4 舍 5 入」就属于数值修约中的一种。

- numpy.around(a)：平均到给定的小数位数。
- numpy.round_(a)：将数组舍入到给定的小数位数。
- numpy.rint(x)：修约到最接近的整数。
- numpy.fix(x, y)：向 0 舍入到最接近的整数。
- numpy.floor(x)：返回输入的底部(标量 x 的底部是最大的整数 i)。
- numpy.ceil(x)：返回输入的上限(标量 x 的底部是最小的整数 i).
- numpy.trunc(x)：返回输入的截断值。

In [94]:
a = np.random.randn(5)
a

array([-0.23738775,  1.31770812, -0.5073555 ,  0.15806831,  1.20973951])

In [95]:
np.around(a)

array([-0.,  1., -1.,  0.,  1.])

In [96]:
np.rint(a)

array([-0.,  1., -1.,  0.,  1.])

In [97]:
np.fix(a)

array([-0.,  1., -0.,  0.,  1.])

#### 求和，求积、差分
- numpy.prod(a, axis, dtype, keepdims)：返回指定轴上的数组元素的乘积。
- numpy.sum(a, axis, dtype, keepdims)：返回指定轴上的数组元素的总和。
- numpy.nanprod(a, axis, dtype, keepdims)：返回指定轴上的数组元素的乘积, 将 NaN 视作 1。
- numpy.nansum(a, axis, dtype, keepdims)：返回指定轴上的数组元素的总和, 将 NaN 视作 0。
- numpy.cumprod(a, axis, dtype)：返回沿给定轴的元素的累积乘积。
- numpy.cumsum(a, axis, dtype)：返回沿给定轴的元素的累积总和。
- numpy.nancumprod(a, axis, dtype)：返回沿给定轴的元素的累积乘积, 将 NaN 视作 1。
- numpy.nancumsum(a, axis, dtype)：返回沿给定轴的元素的累积总和, 将 NaN 视作 0。
- numpy.diff(a, n, axis)：计算沿指定轴的第 n 个离散差分。
- numpy.ediff1d(ary, to_end, to_begin)：数组的连续元素之间的差异。
- numpy.gradient(f)：返回 N 维数组的梯度。
- numpy.cross(a, b, axisa, axisb, axisc, axis)：返回两个(数组）向量的叉积。
- numpy.trapz(y, x, dx, axis)：使用复合梯形规则沿给定轴积分。

In [98]:
a = np.arange(10)

In [99]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.sum(a)

45

In [102]:
a = np.arange(100)
np.diff(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 指数和对数运算
- numpy.exp(x)：计算输入数组中所有元素的指数。
- numpy.log(x)：计算自然对数。
- numpy.log10(x)：计算常用对数。
- numpy.log2(x)：计算二进制对数。

#### 算术运算
- numpy.add(x1, x2)：对应元素相加。
- numpy.reciprocal(x)：求倒数 1/x。
- numpy.negative(x)：求对应负数。
- numpy.multiply(x1, x2)：求解乘法。
- numpy.divide(x1, x2)：相除 x1/x2。
- numpy.power(x1, x2)：类似于 x1^x2。
- numpy.subtract(x1, x2)：减法。
- numpy.fmod(x1, x2)：返回除法的元素余项。
- numpy.mod(x1, x2)：返回余项。
- numpy.modf(x1)：返回数组的小数和整数部分。
- numpy.remainder(x1, x2)：返回除法余数。

In [103]:
a1 = np.random.randint(0, 10, 5)
a2 = np.random.randint(0, 10, 5)
a1, a2

(array([9, 5, 6, 0, 9]), array([4, 2, 4, 7, 0]))

In [104]:
np.add(a1, a2)

array([13,  7, 10,  7,  9])

In [105]:
np.negative(a1)

array([-9, -5, -6,  0, -9])

In [106]:
np.multiply(a1, a2)

array([36, 10, 24,  0,  0])

In [107]:
np.divide(a1, a2)

array([2.25, 2.5 , 1.5 , 0.  ,  inf])

In [108]:
np.power(a1, a2)

array([6561,   25, 1296,    0,    1])

#### 矩阵和向量积
- numpy.dot(a, b)：求解两个数组的点积。
- numpy.vdot(a, b)：求解两个向量的点积。
- numpy.inner(a, b)：求解两个数组的内积。
- numpy.outer(a, b)：求解两个向量的外积。
- numpy.matmul(a, b)：求解两个数组的矩阵乘积。
- numpy.tensordot(a, b)：求解张量点积。
- numpy.kron(a, b)：计算 Kronecker 乘积。

In [111]:
a = np.matrix([[1, 2, 3], [4, 5, 6]])
b = np.matrix([[2, 2], [3, 3], [4, 4]])
np.matmul(a, b)

matrix([[20, 20],
        [47, 47]])

#### 代数运算
- numpy.linalg.cholesky(a)：Cholesky 分解。
- numpy.linalg.qr(a ,mode)：计算矩阵的 QR 因式分解。
- numpy.linalg.svd(a ,full_matrices,compute_uv)：奇异值分解。
- numpy.linalg.eig(a)：计算正方形数组的特征值和右特征向量。
- numpy.linalg.eigh(a, UPLO)：返回 Hermitian 或对称矩阵的特征值和特征向量。
- numpy.linalg.eigvals(a)：计算矩阵的特征值。
- numpy.linalg.eigvalsh(a, UPLO)：计算 Hermitian 或真实对称矩阵的特征值。
- numpy.linalg.norm(x ,ord,axis,keepdims)：计算矩阵或向量范数。
- numpy.linalg.cond(x ,p)：计算矩阵的条件数。
- numpy.linalg.det(a)：计算数组的行列式。
- numpy.linalg.matrix_rank(M ,tol)：使用奇异值分解方法返回秩。
- numpy.linalg.slogdet(a)：计算数组的行列式的符号和自然对数。
- numpy.trace(a ,offset,axis1,axis2,dtype,out)：沿数组的对角线返回总和。
- numpy.linalg.solve(a, b)：求解线性矩阵方程或线性标量方程组。
- numpy.linalg.tensorsolve(a, b ,axes)：为 x 解出张量方程 a x = b
- numpy.linalg.lstsq(a, b ,rcond)：将最小二乘解返回到线性矩阵方程。
- numpy.linalg.inv(a)：计算逆矩阵。
- numpy.linalg.pinv(a ,rcond)：计算矩阵的（Moore-Penrose）伪逆。
- numpy.linalg.tensorinv(a ,ind)：计算 N 维数组的逆。

#### Other Math Compute
- numpy.angle(z, deg)：返回复参数的角度。
- numpy.real(val)：返回数组元素的实部。
- numpy.imag(val)：返回数组元素的虚部。
- numpy.conj(x)：按元素方式返回共轭复数。
- numpy.convolve(a, v, mode)：返回线性卷积。
- numpy.sqrt(x)：平方根。
- numpy.cbrt(x)：立方根。
- numpy.square(x)：平方。
- numpy.absolute(x)：绝对值, 可求解复数。
- numpy.fabs(x)：绝对值。
- numpy.sign(x)：符号函数。
- numpy.maximum(x1, x2)：最大值。
- numpy.minimum(x1, x2)：最小值。
- numpy.nan_to_num(x)：用 0 替换 NaN。
- numpy.interp(x, xp, fp, left, right, period)：线性插值。

### 数组index and 切片
#### 数组索引
我们可以通过索引值（从 0 开始）来访问 Ndarray 中的特定位置元素。NumPy 中的索引和 Python 对 list 索引的方式非常相似，但又有所不同。我们一起来看一下：

首先是，一维数据索引：

In [112]:
a = np.arange(10)

In [113]:
a[1]

1

In [114]:
a[[1, 2, 3]]

array([1, 2, 3])

In [115]:
a = np.arange(20).reshape(4, 5)

In [116]:
a[1, 2]

7

In [118]:
a = a.tolist()
a

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

In [119]:
a[1, 2]

TypeError: list indices must be integers or slices, not tuple

In [120]:
a[1][2]

7

In [121]:
a = np.arange(20).reshape(4, 5)

In [122]:
a[[1, 2], [3, 4]]
# 这里需要注意索引的对应关系。我们实际获取的是 [1, 3]，也就是第 2 行和第 4 列对于的值 8。以及 [2, 4]，也就是第 3 行和第 5 列对应的值 14。

array([ 8, 14])

In [123]:
a = np.arange(30).reshape(2, 5, 3)

In [124]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [125]:
a[[0, 1], [1, 2], [1, 2]]

array([ 4, 23])

#### 数组切片
```python
Ndarray[start: stop: step]
[start: stop: step] = [起始索引: 截止索引: 步长]
```
]

In [126]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
a[: 5]

array([0, 1, 2, 3, 4])

In [128]:
a[5: 10]

array([5, 6, 7, 8, 9])

In [129]:
a[0: 10: 2]

array([0, 2, 4, 6, 8])

In [130]:
# 对于多维数组，我们只需要用逗号 , 分割不同维度即可：
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [131]:
a[0: 3, 2: 4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

#### sort、search、count
```python
numpy.sort(a, axis = -1, kind = 'quicksort', order = None)

```
- a：数组。
- axis：要排序的轴。如果为None，则在排序之前将数组铺平。默认值为 -1，沿最后一个轴排序。
- kind：{'quicksort'，'mergesort'，'heapsort'}，排序算法。默认值为 quicksort。

In [132]:
a = np.random.rand(20).reshape(4, 5)
a

array([[0.25141412, 0.79312078, 0.13825879, 0.29517414, 0.60568423],
       [0.52252102, 0.63365093, 0.31997639, 0.0964661 , 0.20018475],
       [0.42214985, 0.93795423, 0.47363582, 0.71467831, 0.31484512],
       [0.8239203 , 0.2176947 , 0.29598231, 0.61859373, 0.39070299]])

In [133]:
np.sort(a) # 对数组每一行进行排序

array([[0.13825879, 0.25141412, 0.29517414, 0.60568423, 0.79312078],
       [0.0964661 , 0.20018475, 0.31997639, 0.52252102, 0.63365093],
       [0.31484512, 0.42214985, 0.47363582, 0.71467831, 0.93795423],
       [0.2176947 , 0.29598231, 0.39070299, 0.61859373, 0.8239203 ]])

#### Other Sort Way
- numpy.lexsort(keys ,axis)：使用多个键进行间接排序。
- numpy.argsort(a ,axis,kind,order)：沿给定轴执行间接排序。
- numpy.msort(a)：沿第 1 个轴排序。
- numpy.sort_complex(a)：针对复数排序。

#### Search and Count
- argmax(a ,axis,out)：返回数组中指定轴的最大值的索引。
- nanargmax(a ,axis)：返回数组中指定轴的最大值的索引,忽略 NaN。
- argmin(a ,axis,out)：返回数组中指定轴的最小值的索引。
- nanargmin(a ,axis)：返回数组中指定轴的最小值的索引,忽略 NaN。
- argwhere(a)：返回数组中非 0 元素的索引,按元素分组。
- nonzero(a)：返回数组中非 0 元素的索引。
- flatnonzero(a)：返回数组中非 0 元素的索引,并铺平。
- where(条件,x,y)：根据指定条件,从指定行、列返回元素。
- searchsorted(a,v ,side,sorter)：查找要插入元素以维持顺序的索引。
- extract(condition,arr)：返回满足某些条件的数组的元素。
- count_nonzero(a)：计算数组中非 0 元素的数量。

In [134]:
a = np.random.randint(0, 10, 20)
a

array([0, 4, 4, 6, 3, 5, 9, 3, 6, 5, 1, 8, 1, 4, 2, 0, 0, 9, 5, 6])

In [135]:
np.argmax(a)

6

In [136]:
np.argmin(a)

0

In [137]:
np.nonzero(a)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 17, 18, 19]),)

In [138]:
np.count_nonzero(a)

17

In [ ]:
a

这里介绍了NumPy常用的一些方法。在NumPy_Example中我放入了一些NumPy常用的一些数值运算例子。